### ISSUE TITLE
Feature request: Use controller with CardSettingsPhone

### ISSUE THREAD

**Issue by arthurgustin** [codegrue/card_settings#11]
My function creating a phone field is the following:

```dart
static Widget nullablePhoneFormField(TextEditingController controller, String label) {
     return CardSettingsPhone(
       label: label,
       controller: controller,
       validator: (val) {},
     );
   }
```

Here is the console output:

```
I/flutter (  618): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (  618): The following assertion was thrown building CardSettingsPhone(dirty):
I/flutter (  618): 'package:card_settings/widgets/text_fields/card_settings_text.dart': Failed assertion: line 55 pos
I/flutter (  618): 16: 'controller == null || inputMask == null': is not true.
```

A workaround is to instanciate my CardSettingsPhone like this:

```dart
static Widget nullablePhoneFormField(TextEditingController controller, String label) {
     return CardSettingsPhone(
       label: label,
       initialValue: controller.text == "" ? null : int.parse(controller.text),
       onChanged: (int intVal) {
         controller.text = intVal.toString();
       },
       onSaved: (int intVal) {
         controller.text = intVal.toString();
       },
       validator: (val) {},
     );
   }
```

But I don't really like it and sometimes the last characters are not updated and I don't understand why...

**Comment by codegrue** [comment]
This is because the CardSettingsPhone widget hard codes the phone mask string and sends that over to a CardSettingsText widget. That in turn uses a third part controller, MaskedTextController, to govern the formatting. Passing in your own controller would thus eliminate the ability for the phone widget to format the contexts as a phone number. The asset is there to block this usage.

Off the top of my head I'm not sure what an elegant fix would be. Maybe it could be made to allow passing in your own MaskedTextController... Another fix would be to use the CardTextController instead and pass in your own MaskedTextController and an input string and you should be good to go. CardSettingPhone is just a shortcut to avoid this customization.

**Comment by arthurgustin** [comment]
Anyway, I have to store my phone number in String, not int because we can have +XX in Europe, I don't know about united states. For now I use a text field with a custom validator

**Comment by codegrue** [comment]
An optional country code is a nice idea to improve this. It would require a complete overhaul in how formatting works. What is the issue of it becoming an integer?

+1 (800) 555-1212 -> 18005551212
(800) 555-1212 -> 8005551212

**Comment by arthurgustin** [comment]
Phone numbers can start with 0 and + in France :p

Le jeu. 16 août 2018 04:06, Jeff Jorczak <notifications@github.com> a
écrit :

**Comment by AppleEducate** [comment]
Is the workaround still working?

**Comment by arthurgustin** [comment]
Dunno man sorry... its been a while since

Le ven. 15 févr. 2019 à 21:54, Rody Davis <notifications@github.com> a
écrit :

**Comment by AppleEducate** [comment]
Closing for now
