### ISSUE TITLE
CardSettingsPhone null/empty 

### ISSUE THREAD

**Issue by StorminGorman** [codegrue/card_settings#127]
In my application "phone" is an option field.  The CardSettingsPhone widget does not allow for the initialValue to be null and there isn't any flag that I am aware of that allows it to handle this gracefully.... 

`  @override
  Widget build(BuildContext context) {
    return CardSettingsText(
      key: key,
      label: label,
      labelWidth: labelWidth,
      labelAlign: labelAlign,
      contentAlign: contentAlign,
      **initialValue: formatAsPhoneNumber(initialValue.toString()),**`

it decorates the `CardSettingsText` but it calls `initialValue.toString()` and initialValue in this case is an `int`.  If the value is null then it doesn't crash but rather calls the Null.toString() which returns the string `'null'` .. This cannot work for my application.  Unless I am missing something?  If I am not ... would you entertain a pull request fixing this?

**Comment by emem365** [comment]
Just took a peek at the implementation of CardSettingsPhone(), and it looks like it was meant to always have an initialValue. 
As you mentioned, 
`initialValue: formatAsPhoneNumber(initialValue.toString()),`

Maybe a case where no initialValue is given was overlooked. Its an easy fix tho. If @codegrue is accepting contributions, I'd be happy to create a pull request, otherwise you can just make your changes to a fork and use that to get the package from `pubspec.yaml`(Maybe [this](https://stackoverflow.com/questions/54022704/how-to-add-a-package-from-github-flutter) helps)

**Comment by emem365** [comment]
@StorminGorman , [here](https://github.com/emem365/card_settings)'s my fork for this project. Maybe try this fork, or you could see my last commit to see what I did, in case you want to make changes to your own commit. Also, please tell if this works. :)

**Comment by emem365** [comment]
@codegrue , if you're accepting contributions, please tell, so that I can create a pull request. Also. I really appreciate your work on this repo. Super useful 💯. Kudos!

**Comment by mdanics** [comment]
@emem365 your solution works perfectly for me! Also hintText works with your solutions which is great. You should make a PR :)

**Comment by codegrue** [comment]
PR integrated into 1.12.1
